image: python:3.7

stages: 
    - test
    - build

unit-test:
    stage: test
    script:
        - pip install -r assets/requirements.txt
        - python -m unittest

build-and-publish:
    stage: build
    needs:
        - unit-test
    script:
        - pip install build twine
        - python -m build
        - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*
  
    rules:
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
          changes: 
              - setup.py
        - if: $CI_PIPELINE_SOURCE == "tags"
