# put in root folder
[tox]
envlist = py{310, 311}

[testenv]
deps =
    pytest
    pytest-cov
commands =
    python -m pytest \
        --junit-xml=report/{envname}/report.xml \
        --cov-report=term \
        --cov-report=xml:coverage/{envname}/coverage.xml \
        --cov=src \
        tests -s

